manifest:
  remotes:
    - name: molnarc13
      url-base: https://github.com/molnarc13
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: molnarc13
      revision: split-no-encryption
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
  self:
    path: config
