manifest:
  remotes:
    - name: slicemk
      url-base: https://github.com/slicemk
    - name: luberry
      url-base: https://github.com/luberry
  projects:
    - name: zmk
      remote: luberry
      revision: pmw3389
      import: app/west.yml
  self:
    path: config
